In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv(r"C:\Users\Gayatri Varma\Desktop\dup.csv",encoding="ISO-8859-1")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
dataset

dateCrawled  seller offerType  postalCode           brand  \
0       24-03-2016 11:52  privat   Angebot     70435.0      volkswagen   
1       24-03-2016 10:58  privat   Angebot     66954.0            audi   
2       14-03-2016 12:52  privat   Angebot     90480.0            jeep   
3       17-03-2016 16:54  privat   Angebot     91074.0      volkswagen   
4       31-03-2016 17:25  privat   Angebot     60437.0           skoda   
5       04-04-2016 17:36  privat   Angebot     33775.0             bmw   
6       01-04-2016 20:48  privat   Angebot     67112.0         peugeot   
7       21-03-2016 18:54  privat   Angebot     19348.0      volkswagen   
8       04-04-2016 23:42  privat   Angebot     94505.0            ford   
9       17-03-2016 10:53  privat   Angebot     27472.0      volkswagen   
10      26-03-2016 19:54  privat   Angebot     96224.0           mazda   
11      07-04-2016 10:06  privat   Angebot     57290.0      volkswagen   
12      15-03-2016 22:49  privat   Angebot     37269.0      volkswagen   
13      21-03-2016 21:37  privat   Angebot     90762.0      volkswagen   
14      21-03-2016 12:57  privat   Angebot      4177.0          nissan   
15      11-03-2016 21:39  privat   Angebot     24148.0            ford   
16      01-04-2016 12:46  privat   Angebot     38871.0      volkswagen   
17      20-03-2016 10:25  privat   Angebot     65599.0         renault   
18      23-03-2016 15:48  privat   Angebot     88361.0            ford   
19      01-04-2016 22:55  privat   Angebot     49565.0   mercedes_benz   
20      01-04-2016 19:56  privat   Angebot     75365.0      volkswagen   
21      27-03-2016 11:38  privat   Angebot     68309.0             bmw   
22      23-03-2016 14:52  privat   Angebot     49716.0            opel   
23      12-03-2016 19:43  privat   Angebot      9526.0            seat   
24      13-03-2016 20:40  privat   Angebot     35390.0   mercedes_benz   
25      18-03-2016 21:44  privat   Angebot     73765.0             bmw   
26      10-03-2016 19:38  privat   Angebot     31139.0         citroen   
27      07-03-2016 12:51  privat   Angebot     12621.0           honda   
28      09-03-2016 11:56  privat   Angebot     87471.0      volkswagen   
29      08-03-2016 19:55  privat   Angebot     86199.0            fiat   
...                  ...     ...       ...         ...             ...   
371514  11-03-2016 15:50  privat   Angebot     65936.0            opel   
371515  08-03-2016 13:52  privat   Angebot     24850.0            opel   
371516  21-03-2016 23:40  privat   Angebot     38470.0      volkswagen   
371517  26-03-2016 18:36  privat   Angebot     34320.0        chrysler   
371518  01-04-2016 12:59  privat   Angebot     34414.0            audi   
371519  01-04-2016 01:55  privat   Angebot     90439.0          subaru   
371520  07-03-2016 17:06  privat   Angebot     61169.0   mercedes_benz   
371521  03-04-2016 19:56  privat   Angebot     58730.0            opel   
371522  20-03-2016 18:47  privat   Angebot      1217.0      volkswagen   
371523  16-03-2016 17:06  privat   Angebot     56472.0            audi   
371524  02-04-2016 16:43  privat   Angebot     23820.0            opel   
371525  11-03-2016 23:40  privat   Angebot     87700.0      volkswagen   
371526  06-03-2016 21:11  privat   Angebot     60437.0   mercedes_benz   
371527  31-03-2016 18:50  privat   Angebot      4275.0            audi   
371528  25-03-2016 18:48  privat   Angebot     90473.0   mercedes_benz   
371529  21-03-2016 15:36  privat   Angebot     45896.0            seat   
371530  04-04-2016 11:45  privat   Angebot     88477.0         renault   
371531  09-03-2016 11:36  privat   Angebot     18246.0           skoda   
371532  04-04-2016 09:57  privat   Angebot     48653.0      volkswagen   
371533  28-03-2016 13:48  privat   Angebot     75223.0      volkswagen   
371534  02-04-2016 20:37  privat   Angebot     81825.0             bmw   
371535  09-03-2016 13:37  privat   Angebot     51371.0      alfa_romeo   
371536  19-03-201

In [4]:
dataset.isnull().any()

dateCrawled            True
seller                 True
offerType              True
postalCode             True
brand                  True
dateCreated            True
model                  True
lastSeen               True
nrOfPictures           True
name                   True
vehicleType            True
abtest                 True
carage                 True
gearbox                True
powerPS                True
kilometer              True
monthOfRegistration    True
fuelType               True
notRepairedDamage      True
price                  True
dtype: bool

In [5]:
dataset.dropna(inplace=True)

In [6]:
dataset

dateCrawled  seller offerType  postalCode          brand  \
3       17-03-2016 16:54  privat   Angebot     91074.0     volkswagen   
4       31-03-2016 17:25  privat   Angebot     60437.0          skoda   
5       04-04-2016 17:36  privat   Angebot     33775.0            bmw   
6       01-04-2016 20:48  privat   Angebot     67112.0        peugeot   
7       21-03-2016 18:54  privat   Angebot     19348.0     volkswagen   
10      26-03-2016 19:54  privat   Angebot     96224.0          mazda   
11      07-04-2016 10:06  privat   Angebot     57290.0     volkswagen   
14      21-03-2016 12:57  privat   Angebot      4177.0         nissan   
17      20-03-2016 10:25  privat   Angebot     65599.0        renault   
18      23-03-2016 15:48  privat   Angebot     88361.0           ford   
19      01-04-2016 22:55  privat   Angebot     49565.0  mercedes_benz   
20      01-04-2016 19:56  privat   Angebot     75365.0     volkswagen   
21      27-03-2016 11:38  privat   Angebot     68309.0            bmw   
23      12-03-2016 19:43  privat   Angebot      9526.0           seat   
24      13-03-2016 20:40  privat   Angebot     35390.0  mercedes_benz   
25      18-03-2016 21:44  privat   Angebot     73765.0            bmw   
27      07-03-2016 12:51  privat   Angebot     12621.0          honda   
28      09-03-2016 11:56  privat   Angebot     87471.0     volkswagen   
29      08-03-2016 19:55  privat   Angebot     86199.0           fiat   
30      03-04-2016 15:48  privat   Angebot     53879.0  mercedes_benz   
33      25-03-2016 21:48  privat   Angebot     39179.0            bmw   
34      17-03-2016 18:55  privat   Angebot     67071.0  mercedes_benz   
38      01-04-2016 17:45  privat   Angebot     10551.0     volkswagen   
39      25-03-2016 15:50  privat   Angebot     22767.0  mercedes_benz   
43      13-03-2016 15:47  privat   Angebot     59174.0           mini   
45      29-03-2016 18:57  privat   Angebot     84180.0        renault   
46      15-03-2016 18:59  privat   Angebot     53604.0            bmw   
47      04-04-2016 00:38  privat   Angebot     86157.0            bmw   
49      04-04-2016 14:06  privat   Angebot     35576.0  mercedes_benz   
55      26-03-2016 10:39  privat   Angebot     56759.0           opel   
...                  ...     ...       ...         ...            ...   
371495  13-03-2016 12:51  privat   Angebot     49536.0           opel   
371496  26-03-2016 23:25  privat   Angebot     63065.0          smart   
371497  12-03-2016 16:48  privat   Angebot     21147.0        porsche   
371499  07-03-2016 09:54  privat   Angebot     77694.0  mercedes_benz   
371503  14-03-2016 16:52  privat   Angebot     86609.0  mercedes_benz   
371504  15-03-2016 01:51  privat   Angebot     72766.0  mercedes_benz   
371505  13-03-2016 15:45  privat   Angebot     30519.0  mercedes_benz   
371506  22-03-2016 10:37  privat   Angebot     91301.0          honda   
371507  15-03-2016 20:25  privat   Angebot     60439.0     volkswagen   
371508  04-04-2016 14:41  privat   Angebot     17509.0           opel   
371513  05-03-2016 15:54  privat   Angebot     88213.0           opel   
371515  08-03-2016 13:52  privat   Angebot     24850.0           opel   
371516  21-03-2016 23:40  privat   Angebot     38470.0     volkswagen   
371517  26-03-2016 18:36  privat   Angebot     34320.0       chrysler   
371518  01-04-2016 12:59  privat   Angebot     34414.0           audi   
371519  01-04-2016 01:55  privat   Angebot     90439.0         subaru   
371521  03-04-2016 19:56  privat   Angebot     58730.0           opel   
371522  20-03-2016 18:47  privat   Angebot      1217.0     volkswagen   
371524  02-04-2016 16:43  privat   Angebot     23820.0           opel   
371526  06-03-2016 21:11  privat   Angebot     60437.0  mercedes_benz   
371527  31-03-2016 18:50  privat   Angebot      4275.0           audi   
371528  25-03-2016 18:48  privat   Angebot     90473.0  mercedes_benz   
371529  21-03-2016 15:36  privat   Angebot     45896.0           seat  

In [7]:
dataset.isnull().any()

dateCrawled            False
seller                 False
offerType              False
postalCode             False
brand                  False
dateCreated            False
model                  False
lastSeen               False
nrOfPictures           False
name                   False
vehicleType            False
abtest                 False
carage                 False
gearbox                False
powerPS                False
kilometer              False
monthOfRegistration    False
fuelType               False
notRepairedDamage      False
price                  False
dtype: bool

In [8]:
dataset

dateCrawled  seller offerType  postalCode          brand  \
3       17-03-2016 16:54  privat   Angebot     91074.0     volkswagen   
4       31-03-2016 17:25  privat   Angebot     60437.0          skoda   
5       04-04-2016 17:36  privat   Angebot     33775.0            bmw   
6       01-04-2016 20:48  privat   Angebot     67112.0        peugeot   
7       21-03-2016 18:54  privat   Angebot     19348.0     volkswagen   
10      26-03-2016 19:54  privat   Angebot     96224.0          mazda   
11      07-04-2016 10:06  privat   Angebot     57290.0     volkswagen   
14      21-03-2016 12:57  privat   Angebot      4177.0         nissan   
17      20-03-2016 10:25  privat   Angebot     65599.0        renault   
18      23-03-2016 15:48  privat   Angebot     88361.0           ford   
19      01-04-2016 22:55  privat   Angebot     49565.0  mercedes_benz   
20      01-04-2016 19:56  privat   Angebot     75365.0     volkswagen   
21      27-03-2016 11:38  privat   Angebot     68309.0            bmw   
23      12-03-2016 19:43  privat   Angebot      9526.0           seat   
24      13-03-2016 20:40  privat   Angebot     35390.0  mercedes_benz   
25      18-03-2016 21:44  privat   Angebot     73765.0            bmw   
27      07-03-2016 12:51  privat   Angebot     12621.0          honda   
28      09-03-2016 11:56  privat   Angebot     87471.0     volkswagen   
29      08-03-2016 19:55  privat   Angebot     86199.0           fiat   
30      03-04-2016 15:48  privat   Angebot     53879.0  mercedes_benz   
33      25-03-2016 21:48  privat   Angebot     39179.0            bmw   
34      17-03-2016 18:55  privat   Angebot     67071.0  mercedes_benz   
38      01-04-2016 17:45  privat   Angebot     10551.0     volkswagen   
39      25-03-2016 15:50  privat   Angebot     22767.0  mercedes_benz   
43      13-03-2016 15:47  privat   Angebot     59174.0           mini   
45      29-03-2016 18:57  privat   Angebot     84180.0        renault   
46      15-03-2016 18:59  privat   Angebot     53604.0            bmw   
47      04-04-2016 00:38  privat   Angebot     86157.0            bmw   
49      04-04-2016 14:06  privat   Angebot     35576.0  mercedes_benz   
55      26-03-2016 10:39  privat   Angebot     56759.0           opel   
...                  ...     ...       ...         ...            ...   
371495  13-03-2016 12:51  privat   Angebot     49536.0           opel   
371496  26-03-2016 23:25  privat   Angebot     63065.0          smart   
371497  12-03-2016 16:48  privat   Angebot     21147.0        porsche   
371499  07-03-2016 09:54  privat   Angebot     77694.0  mercedes_benz   
371503  14-03-2016 16:52  privat   Angebot     86609.0  mercedes_benz   
371504  15-03-2016 01:51  privat   Angebot     72766.0  mercedes_benz   
371505  13-03-2016 15:45  privat   Angebot     30519.0  mercedes_benz   
371506  22-03-2016 10:37  privat   Angebot     91301.0          honda   
371507  15-03-2016 20:25  privat   Angebot     60439.0     volkswagen   
371508  04-04-2016 14:41  privat   Angebot     17509.0           opel   
371513  05-03-2016 15:54  privat   Angebot     88213.0           opel   
371515  08-03-2016 13:52  privat   Angebot     24850.0           opel   
371516  21-03-2016 23:40  privat   Angebot     38470.0     volkswagen   
371517  26-03-2016 18:36  privat   Angebot     34320.0       chrysler   
371518  01-04-2016 12:59  privat   Angebot     34414.0           audi   
371519  01-04-2016 01:55  privat   Angebot     90439.0         subaru   
371521  03-04-2016 19:56  privat   Angebot     58730.0           opel   
371522  20-03-2016 18:47  privat   Angebot      1217.0     volkswagen   
371524  02-04-2016 16:43  privat   Angebot     23820.0           opel   
371526  06-03-2016 21:11  privat   Angebot     60437.0  mercedes_benz   
371527  31-03-2016 18:50  privat   Angebot      4275.0           audi   
371528  25-03-2016 18:48  privat   Angebot     90473.0  mercedes_benz   
371529  21-03-2016 15:36  privat   Angebot     45896.0           seat  

In [9]:
x=dataset.iloc[:,10:19].values

In [10]:
x

array([['kleinwagen', 'test', 18.0, ..., 6, 'benzin', 'nein'],
       ['kleinwagen', 'test', 11.0, ..., 7, 'diesel', 'nein'],
       ['limousine', 'test', 24.0, ..., 10, 'benzin', 'ja'],
       ...,
       ['bus', 'control', 19.0, ..., '3', 'benzin', 'nein'],
       ['cabrio', 'test', 19.0, ..., '3', 'benzin', 'nein'],
       ['bus', 'test', 23.0, ..., '3', 'diesel', 'nein']], dtype=object)

In [11]:
x.shape

(260964, 9)

In [12]:
y=dataset.iloc[:,19:20].values

In [13]:
y

array([[1500.],
       [3600.],
       [ 650.],
       ...,
       [1150.],
       [1199.],
       [9200.]])

In [14]:
y.shape

(260964, 1)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
le4=LabelEncoder()

In [17]:
x

array([['kleinwagen', 'test', 18.0, ..., 6, 'benzin', 'nein'],
       ['kleinwagen', 'test', 11.0, ..., 7, 'diesel', 'nein'],
       ['limousine', 'test', 24.0, ..., 10, 'benzin', 'ja'],
       ...,
       ['bus', 'control', 19.0, ..., '3', 'benzin', 'nein'],
       ['cabrio', 'test', 19.0, ..., '3', 'benzin', 'nein'],
       ['bus', 'test', 23.0, ..., '3', 'diesel', 'nein']], dtype=object)

In [18]:
x[:,0]=le.fit_transform(x[:,0])

In [19]:
x[:,1]=le1.fit_transform(x[:,1])

In [20]:
x[:,3]=le2.fit_transform(x[:,3])

In [21]:
x[:,7]=le3.fit_transform(x[:,7])

In [22]:
x[:,8]=le4.fit_transform(x[:,8])

In [23]:
x

array([[4, 1, 18.0, ..., 6, 1, 1],
       [4, 1, 11.0, ..., 7, 3, 1],
       [6, 1, 24.0, ..., 10, 1, 0],
       ...,
       [1, 0, 19.0, ..., '3', 1, 1],
       [2, 1, 19.0, ..., '3', 1, 1],
       [1, 1, 23.0, ..., '3', 3, 1]], dtype=object)

In [24]:
x.shape

(260964, 9)

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
oh=OneHotEncoder()
oh1=OneHotEncoder()

In [27]:
oh = OneHotEncoder(categorical_features=[0])
x = oh.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [28]:
x.shape

(260964, 16)

In [29]:
x=x[:,1:]

In [30]:
x.shape

(260964, 15)

In [31]:
oh1 = OneHotEncoder(categorical_features=[13])
x = oh1.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [32]:
x.shape

(260964, 21)

In [33]:
x=x[:,1:]

In [34]:
x.shape

(260964, 20)

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=0)

In [36]:
import keras

Using TensorFlow backend.


In [37]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
model=Sequential()

In [39]:
model.add(Dense(input_dim=20,init="random_uniform",output_dim=20,activation="relu"))

Instructions for updating:
Colocations handled automatically by placer.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=20, activation="relu", units=20, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [40]:
model.add(Dense(init="random_uniform",output_dim=15))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=15, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [41]:
model.add(Dense(init="random_uniform",output_dim=5))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=5, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [42]:
model.add(Dense(init="random_uniform",output_dim=1))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [43]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mse'])

In [44]:
model.fit(x_train,y_train,epochs=50,batch_size=8)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
208771/208771 [==============================] - 68s 328us/step - loss: 146730804833.6055 - mean_squared_error: 146730804833.6055
Epoch 2/50
208771/208771 [==============================] - 58s 276us/step - loss: 146720113635.2120 - mean_squared_error: 146720113635.2120
Epoch 3/50
208771/208771 [==============================] - 66s 315us/step - loss: 146717436078.5419 - mean_squared_error: 146717436078.5419
Epoch 4/50
208771/208771 [==============================] - 68s 327us/step - loss: 146709678243.9193 - mean_squared_error: 146709678243.9193
Epoch 5/50
208771/208771 [==============================] - 60s 289us/step - loss: 146705732970.5549 - mean_squared_error: 146705732970.5549
Epoch 6/50
208771/208771 [==============================] - 53s 256us/step - loss: 146707854072.4272 - mean_squared_error: 146707854072.4272
Epoch 7/50
208771/208771 [==============================] - 67s 320us/step - loss: 146708879331.7399 - mea

In [45]:
model.save("project_class.h5")

In [46]:
y_train.shape

(208771, 1)

In [47]:
y_pred=model.predict(x_test)

In [48]:
y_pred

array([[ 730.5676],
       [4821.1636],
       [2246.0315],
       ...,
       [-232.0505],
       [2877.1428],
       [5676.4917]], dtype=float32)

In [49]:
y_test

array([[1295.],
       [3100.],
       [1800.],
       ...,
       [1750.],
       [2200.],
       [5150.]])

In [50]:
y_pred

array([[ 730.5676],
       [4821.1636],
       [2246.0315],
       ...,
       [-232.0505],
       [2877.1428],
       [5676.4917]], dtype=float32)

In [51]:
y_pred[9]

array([3206.1028], dtype=float32)

In [52]:
y_test[9]

array([2199.])

In [74]:
y_pred[7000]

array([5962.762], dtype=float32)

In [75]:
y_test[7000]

array([3850.])

In [55]:
y_test[100]

array([5099.])

In [56]:
y_pred[100]

array([6531.0386], dtype=float32)

In [68]:
y_pred[10000]

array([2880.305], dtype=float32)

In [69]:
y_test[10000]

array([1050.])

In [70]:
from sklearn.metrics import r2_score

In [71]:
r2_score(y_test,y_pred)*100

1.0951906152056545

In [61]:
from sklearn.metrics import mean_squared_error

In [62]:
mean_squared_error(y_test,y_pred)

2455187741.6740904

In [63]:
from sklearn.metrics import mean_absolute_error

In [64]:
mean_absolute_error(y_test,y_pred)

3815.6068060880075